---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  labels:
    name: redis-sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    app: redis-sentinel
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: redis-sentinel
        image: kumojin/redis-sentinel:5.0.8
        imagePullPolicy: Always
        env:
          - name: REDIS_MASTER
            value: redis.redis
          - name: REDIS_SENTINEL
            value: redis-sentinel
        readinessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 15
          periodSeconds: 20
      
        ports:
          - containerPort: 26379
