---
apiVersion: v1
kind: Service
metadata:
  namespace: redis
  labels:
    name: redis-sentinel
    role: service
  name: redis-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: redis
spec:
  serviceName: redis-sentinel
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: redis-sentinel
        image: kumojin/redis:sentinel-5.0.8
        env:
          - name: REDIS_MASTER
            value: redis-0.redis
          - name: REDIS_SENTINEL
            value: redis-sentinel
        ports:
          - containerPort: 26379
        volumeMounts:
          - name: redis-sentinel-data
            mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-sentinel-data
      spec:
        storageClassName: redis-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
